# Generated by Django 3.2.8 on 2021-10-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211025_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedata',
            name='website_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
